# https://github.com/jekyll/minim
title: Breno Cesar Tech Blog
author:
  name: brenocrs
  email: brenocrs230388@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Some notes and thoughts about technology.
url: "https://brenocrs.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true # set to true to show excerpts on the homepage
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:   
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    github:  brenocrs
    linkedin: brenocesar
